In [1]:
# 한줄 주석
# 여러줄
# 주석 = ctrl + /

...
이렇게주석처리가능
...

1+2


NameError: name '이렇게주석처리가능' is not defined

- 아르테미스 달탐사
- 파이썬 데이터 분석
    -  ai 스쿨
    

- 넘파이 실습

In [ ]:

math = [67,43,14,89,50] # 수학점수
eng = [78,98,56,87,44] #영어점수

print(math+eng)

[67, 43, 14, 89, 50, 78, 98, 56, 87, 44]


In [ ]:
# 리스트로 합 구하기
hap = []
for i in range(len(math)): #0,1,2,3,4
    hap.append(math[i] + eng[i])

hap 

[145, 141, 70, 176, 94]

In [ ]:
# 넘파이 배열로 합 구하기
import numpy as np

mathnum = np.array(math)
engnum = np.array(eng)

print(mathnum)
engnum

[67 43 14 89 50]


array([78, 98, 56, 87, 44])

In [ ]:
mathnum + engnum

array([145, 141,  70, 176,  94])

In [ ]:
# bmi 구하기

height = [1.68,1.76,1.59,1.86,1.73] # 키 (단위: m)
weight = [70,82,52,92,79] # 몸무게 (단위: kg)

#넘파이 배열로 구하기
import numpy as np

heightsnum = np.array(height)
weightsnum = np.array(weight)

# 주피터는 print생략가능 하지만 마지막 줄만 값 나옴
bmi = weightsnum / (heightsnum**2)

print('대상자의 bmi:', bmi)


대상자의 bmi: [24.8015873  26.47210744 20.56880661 26.59266967 26.3958034 ]


# pandas 예제실습

In [ ]:
# pandas  예제 실습
import pandas as pd

#series 생성
num = [i for i in range(1,11)]

seriesnum = pd.Series(num)
seriesnum


0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [ ]:
# series 요약통계

seriesnum.sum()
seriesnum.mean() # 평균
seriesnum.std() # 표준편차
seriesnum.median()

seriesnum.describe() # 요약통계


count    10.00000
mean      5.50000
std       3.02765
min       1.00000
25%       3.25000
50%       5.50000
75%       7.75000
max      10.00000
dtype: float64

In [ ]:
# 딕셔너리 시리즈로 

num2 = pd.Series({'a':1,'b':2,'c':3,'d':4})
num2


a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
num2[0] # 인덱스 번호로 호출
num2['c'] # 인덱스 이름으로 추출


/tmp/ipykernel_4560/3467237651.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  num2[0] # 인덱스 번호로 호출


3

In [ ]:
# 결측치 확인

s = pd.Series([1,2,np.nan,4,5])
s

0    1.0
1    2.0
2    NaN
3    4.0
4    5.0
dtype: float64

In [ ]:
# 결측치 확인

s.isnull()

s.isnull().sum()

1

In [ ]:
# 결측치 처리 - 채워넣기
s.fillna(0) # 원본 저장 x

s.fillna(0,inplace=True) # 원본에 저장 o

s


0    1.0
1    2.0
2    0.0
3    4.0
4    5.0
dtype: float64

In [ ]:
# 결측치 삭제 처리

a = pd.Series([1,2,np.nan,4,5,7,np.nan])
a


0    1.0
1    2.0
2    NaN
3    4.0
4    5.0
5    7.0
6    NaN
dtype: float64

In [ ]:
a.dropna()

0    1.0
1    2.0
3    4.0
4    5.0
5    7.0
dtype: float64

In [ ]:
# dataframe 생성 표 형식으로 생성됨

nums = [[1,2,3],[4,5,6],[7,8,9]]
dfnums = pd.DataFrame(nums)
dfnums

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
# 데이터프레임 정보

dfnums.shape # 속성, =3개의 행과열, 행렬 정보
dfnums.shape[0] 
dfnums[0].sum() #0번 열의 합
dfnums+3 # 각각 3더하기



0   1   2
0   4   5   6
1   7   8   9
2  10  11  12

In [ ]:
#행, 열별로 합계

dfnums.sum(axis=1) # 가로방향 행별 합계
dfnums.sum(axis=0) # 세로방향 각 열별 합계


0    12
1    15
2    18
dtype: int64

- 컬럼명 생성

In [ ]:
# 컬럼명 생성
users = [['철수',160,16],['민수',170,18],['짱구',130,13],['영희',110,8]]
dfusers = pd.DataFrame(users)
dfusers


0    1   2
0  철수  160  16
1  민수  170  18
2  짱구  130  13
3  영희  110   8

In [ ]:
# 컬럼명 생성

dfusers.columns = ['name','height','age']
dfusers


name  height  age
0   철수     160   16
1   민수     170   18
2   짱구     130   13
3   영희     110    8

In [ ]:
# 인덱스명 

dfusers.index = ['학생1','학생2','학생3','학생4']
dfusers

name  height  age
학생1   철수     160   16
학생2   민수     170   18
학생3   짱구     130   13
학생4   영희     110    8

In [ ]:
dfusers['height'].sum()

570

- 인덱스로 행 추출

In [ ]:
# 인덱스로 행 추출

dfusers.loc['학생1']

dfusers.loc[['학생1','학생3']]

dfusers.loc['학생1','age']
dfusers.loc['학생3',['name','age']]


name    짱구
age     13
Name: 학생3, dtype: object

In [ ]:
# 인덱스 번호로 추출

dfusers.iloc[0]
dfusers.iloc[[0,2]]
dfusers.iloc[0,0]
dfusers.iloc[0,[0,1]]


name       철수
height    160
Name: 학생1, dtype: object

- 새로운 열 생성

In [ ]:
# 새로운 열 생성

dfusers['weight'] = [80,67,30,17]
dfusers


name  height  age  weight
학생1   철수     160   16      80
학생2   민수     170   18      67
학생3   짱구     130   13      30
학생4   영희     110    8      17

In [ ]:
# 새로운 열 위치 지정
 
dfusers.insert(2,'Type',['A','B','AB','O'])
dfusers

name  height Type type  age  weight
학생1   철수     160    A    A   16      80
학생2   민수     170    B    B   18      67
학생3   짱구     130   AB   AB   13      30
학생4   영희     110    O    O    8      17

In [ ]:
# 부울링 인덱싱

dfusers['height'] >= 150
dfusers['Type'] == 'A'

학생1     True
학생2    False
학생3    False
학생4    False
Name: Type, dtype: bool

In [ ]:
(dfusers['height'] >= 150) & (dfusers['weight'] <= 70) # and

(dfusers['height'] >= 150) | (dfusers['weight'] <= 70) # or


학생1    True
학생2    True
학생3    True
학생4    True
dtype: bool

In [ ]:
# 정렬

dfusers.sort_values(by = 'age') # 오름차순

dfusers.sort_values(by = 'age',ascending=False) # 내림차순


name  height Type type  age  weight
학생2   민수     170    B    B   18      67
학생1   철수     160    A    A   16      80
학생3   짱구     130   AB   AB   13      30
학생4   영희     110    O    O    8      17

In [ ]:
# 열 삭제

dfusers.drop('age',axis=1,inplace=True) # 원본에 추가됨
dfusers

name  height Type type  weight
학생1   철수     160    A    A      80
학생2   민수     170    B    B      67
학생3   짱구     130   AB   AB      30
학생4   영희     110    O    O      17

In [ ]:
del dfusers['type']
dfusers

name  height  weight
학생1   철수     160      80
학생2   민수     170      67
학생3   짱구     130      30
학생4   영희     110      17

- 람다함수

In [ ]:
(lambda x: 2*x)(2)

4